#!/usr/bin/env bash
# this script giving information about the school file

file_name="school"
if [[ -e $file_name ]]
then
	echo "school file exists"
	if [[ ! -s $file_name ]]
	then
		echo "school file is empty"
	else
		echo "school file is not empty"
	fi
	if [[ -f $file_name ]]
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
