#!/usr/bin/env bash
# Configures an Nginx server to listen on port 80.

nginx_config="/etc/nginx/sites-available/default"
if ! grep -q "listen 80;" "$nginx_config"; then
    sed -i 's/listen 80;/listen 80 default_server;/g' "$nginx_config"

    service nginx restart
fi
