#!/usr/bin/env bash
# This script diplays number from 1 to 100 In a list format
# Displays FizzBuzz when the number is a multiple of 3 and 5
# Fizz when the number is multiple of 3
# Buzz when the number is a multiple of 5
# Displays the number.

count=1
while [ $count -le 100 ]
do
	if [[ $((count % 3)) -eq 0 && $((count % 5)) -eq 0 ]]
	then
		echo "FizzBuzz"
	elif [[ $((count % 3)) -eq 0 ]]
	then
		echo "Fizz"
	elif [[ $((count % 5)) -eq 0 ]]
	then
		echo "Buzz"
	else
		echo "$count"
	fi
	((count++))
done
