#!/usr/bin/env bash
# This script display number from 1 to 20
# displays 4 and  bad luck from China for the 4th loop iteration
# displays 9 and  bad luck from Japan for the 9th loop iteration
# displays 17 and bad luck from Italy for the 17th loop iteration

count=1
while [ $count -le 20 ]
do
	case $count in
	4)
		echo "$count"
		echo "bad luck from China"
		;;
	9)
		echo "$count"
		echo "bad luck from Japan"
		;;
	17)
		echo "$count"
		echo "bad luck from Italy"
		;;
	*)
		echo "$count"
		;;
	esac
	((count++))
done
