#!/usr/bin/env bash
# This script is for diplaying the content of the current 
# Directory only the part of the name after the first dash is displayed 

for file in *
do
	if [[ -f "$file" && ! "$file" == .* ]]
	then
		name=$(echo "$file" | cut -d '-' -f2-)
		echo "$name"
	fi
done
